run:
  timeout: 5m
  tests: true
  skip-dirs:
    - web/node_modules
    - vendor

linters:
  enable:
    - gocritic
    - godot
    - gofmt
    - govet
    - staticcheck
    - unused

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
